[project]
name = "week10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mlflow>=3.5.0",
    "numpy>=2.2.6",
    "seaborn>=0.13.2",
]
